import React from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import clsx from 'clsx';
import { ConfigProvider } from 'antd'
import 'antd/dist/reset.css'
import '@/shared/styles/globals.scss';
import ThemeProvider from '@/shared/providers/ThemeProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Main',
  description: 'Generated by create next app',
};

interface IMainPageLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IMainPageLayoutProps) {
  return (
    <html lang="en">
      <body className={clsx(geistSans.variable, geistMono.variable)}>
        <ConfigProvider>
          <ThemeProvider>
          {children}
          </ThemeProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}